name: Deploy to AWS App Runner - PROD

on:
  workflow_dispatch: # Esto permite el despliegue manual
    inputs:
      environment:
        description: 'Choose the environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/prod' || github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_REGION: ${{ secrets.AWS_REGION_PROD }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and tag Docker image
        env:
          REPOSITORY_NAME: nuciari/bff
        run: |
          docker build -t $REPOSITORY_NAME:latest .

      - name: Push Docker image to ECR
        env:
          REPOSITORY_NAME: nuciari/bff
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          AWS_REGION: ${{ secrets.AWS_REGION_PROD }}
        run: |
          docker tag $REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest

      - name: Notify success
        run: echo "Deployment to AWS App Runner was successful!"
